### ISSUE TITLE
feat(top-app-bar): migrate toolbar to top-app-bar

### ISSUE THREAD

**Issue by CaerusKaru** [angular/components#13964]
#### Bug, feature request, or proposal:

feature request

#### What is the expected behavior?

Toolbar should be migrated to top-bar, there should be no toolbar component

#### What is the current behavior?

Toolbar, but no top- or bottom-bar

#### What is the use-case or motivation for changing an existing behavior?

The spec has been updated to not include a toolbar, instead allowing for "App bars", both [top-](https://material.io/design/components/app-bars-top.html) and [bottom-](https://material.io/design/components/app-bars-bottom.html).

#### Is there anything else we should know?

MDC is also doing this, and it is being tracked [here](https://github.com/material-components/material-components-web/issues/3040)

## Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [ ] Stub existing component API
- [ ] Hook up MDC foundation and adapter
- [ ] Add remaining features on top of MDC implementation
- [x] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [ ] Copy existing unit tests and ensure they all pass
- [ ] Copy existing e2e tests and ensure they all pass (if any)
- [ ] Verify SSR support in universal-app/
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation
## Known issues & visual differences

**Comment by mhosman** [comment]
🤤🤤🤤🤤🤤

![ezgif-1-b45d38fe5d3a](https://user-images.githubusercontent.com/5334175/48908279-93d3fe00-ee48-11e8-90b1-e658d36ac21d.gif)

**Comment by Splaktar** [comment]
Related: https://material.io/develop/web/components/top-app-bar/

**Comment by Splaktar** [comment]
For reference, here's [the merged PR](https://github.com/material-components/material-components-web/pull/2225) for MDC's `mdc-top-app-bar`.

@mhosman that's a `bottom-app-bar` rather than `top-app-bar`. I've opened https://github.com/angular/components/issues/16367 to track the creation of a `mat-bottom-app-bar`.

**Comment by Splaktar** [comment]
[Docs and a demo](https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar) for the MDC Top App Bar are now available.

**Comment by jelbourn** [comment]
Closing this since we don't plan on migrating `<mat-toolbar>` to match the "appbar" design from 2018+. We may eventually introduce a _new_ appbar component that supersedes toolbar, but we don't have any immediate plans for this.
