### ISSUE TITLE
Build MDC-based chips

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16173]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [ ] Stub existing component API
- [ ] Hook up MDC foundation and adapter
- [ ] Add remaining features on top of MDC implementation
- [ ] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [ ] Copy existing unit tests and ensure they all pass
- [ ] Copy existing e2e tests and ensure they all pass (if any)
- [ ] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
* The current chips implementation uses `role="listbox"`. For the MDC-based version, we want to introduce different interaction-pattern variants, e.g.
```html
<!-- role="grid" -->
<mat-chip-grid>
  <mat-chip-cell> ... </mat-chip-cell>
</mat-chip-grid>

<!-- role="listbox" -->
<mat-chip-listbox>
  <mat-chip-option> ... </mat-chip-option>
</mat-chip-listbox>
```
All of the variants of the chip-set/chip should extend from one common base.

* We likely want to remove the idea of `selected` from the base chip since it only really applies in the `listbox` model

### Known issues & visual differences

**Comment by vanessanschmitt** [comment]
Status update: 
### Tasks
* [x]  Scaffold empty classes, assets, demo, build config, etc.
* [x]  Stub existing component API
* [x]  Hook up MDC foundation and adapter
* [ ]  Add remaining features on top of MDC implementation **(In progress)**
* [x]  Test dark theme
* [ ]  Test RTL
* [ ]  Test with screen-readers
* [ ]  Copy existing unit tests and ensure they all pass
* [ ]  Copy existing e2e tests and ensure they all pass (if any)
* [ ]  Verify SSR support in `universal-app/`
* [ ]  Verify no size regression
* [ ]  Create test harness
* [ ]  Create schematics for migration
* [ ]  Create user documentation
