### ISSUE TITLE
Build MDC-based slider

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16175]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [x] Add remaining features on top of MDC implementation
- [x] Test dark theme
- [x] Test RTL
- [ ] Test with screen-readers
- [x] Copy existing unit tests and ensure they all pass
- [x] Copy existing e2e tests and ensure they all pass (if any)
- [x] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [x] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
* We need to confirm with MDC if the slider is ready for us to wrap
* We want to avoid any dependency on HammerJS in the MDC-based slider
* Will need to verify behavior for both mouse and touch

### Known issues & visual differences
