### ISSUE TITLE
Build MDC-based snackbar

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16176]
### Tasks
- [ ] Scaffold empty classes, assets, demo, build config, etc.
- [ ] Stub existing component API
- [ ] Hook up MDC foundation and adapter
- [ ] Add remaining features on top of MDC implementation
- [ ] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [ ] Copy existing unit tests and ensure they all pass
- [ ] Copy existing e2e tests and ensure they all pass (if any)
- [ ] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Known issues & visual differences
