### ISSUE TITLE
Build MDC-based radio-buttons

### ISSUE THREAD

**Issue by jelbourn** [angular/components#16174]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [ ] Stub existing component API
- [ ] Hook up MDC foundation and adapter
- [ ] Add remaining features on top of MDC implementation
- [ ] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [ ] Copy existing unit tests and ensure they all pass
- [ ] Copy existing e2e tests and ensure they all pass (if any)
- [ ] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
In the current radio implementation, `MatRadioGroup` knows about its `MatRadioButtons` _and_ `MatRadioButton` knows about its parent `MatRadioGroup`. Each then wants to update the other when they're updated. This makes the coordination between the two somewhat messy. Going forward we want to only have a one-way knowledge here.

### Known issues & visual differences

**Comment by devversion** [comment]
Note: We should pay attention to #19611 as part of finishing up the MDC-based radio implementation.
