### ISSUE TITLE
Build MDC-based checkbox

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16195]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [x] Add remaining features on top of MDC implementation
- [x] Test dark theme
- [x] Test RTL
- [x] Test with screen-readers
- [x] Copy existing unit tests and ensure they all pass
- [x] Copy existing e2e tests and ensure they all pass (if any)
- [x] Verify SSR support in `universal-app/`
- [x] Verify no size regression
- [x] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
* Currently using `MatRippleRenderer` directly rather than `MatRipple` or `MDCRipple`. We should work with the MDC team to make sure we can use the `MDCRipple` in the long run. 

### Known issues & visual differences
* `ripple` property is no longer available on `MatCheckbox`.
