### ISSUE TITLE
Build MDC-based button

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16196]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [ ] Add remaining features on top of MDC implementation
- [ ] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [ ] Copy existing unit tests and ensure they all pass
- [ ] Copy existing e2e tests and ensure they all pass (if any)
- [ ] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
* Consider supporting button[mat-outlined-button]
* Should each button type have a unique top level class? e.g. mdc-mat-icon-button
* Consider if we want to add a "appearance/type" input to button, similar to form field (outline/stroked, flat, raised)

### Known issues & visual differences
* Disabled FAB does not look disabled
* Anchor button does not look disabled
* No focused state
* Icon buttons are not colored by theme
* Missing JSDoc comments on some exported symbols

**Comment by Suresh918** [comment]
What are these MDC based components... What is the difference between actual angular components and these? Can you please give the details..

**Comment by mmalerba** [comment]
These are versions of the same components we already have, with the same APIs, but based on top of the Material Design team's [canonical implementation](https://github.com/material-components/material-components-web). They're not ready for use in applications yet which is why all of the code is currently under `@angular/material-experimental`.

**Comment by DaSchTour** [comment]
Hopefully this will also include buttons with leading icons?
