### ISSUE TITLE
Build MDC-based slide-toggle

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16248]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [x] Add remaining features on top of MDC implementation
- [ ] Test dark theme
- [ ] Test RTL
- [ ] Test with screen-readers
- [x] Copy existing unit tests and ensure they all pass
- [x] Copy existing e2e tests and ensure they all pass (if any)
- [x] Verify SSR support in `universal-app/`
- [x] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Breaking changes
* The MDC-based `mat-slide-toggle` drops the dependency on Hammer.js and as a result doesn't support dragging gestures
* As a result of dragging gestures not being supported, the `dragChange` event won't emit

### Known issues & visual differences

**Comment by crisbeto** [comment]
Size comparison: https://github.com/mmalerba/mdc-size-comparison/tree/slide-toggle.
