### ISSUE TITLE
Build MDC-based menu

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16247]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [x] Add remaining features on top of MDC implementation
- [x] Test dark theme
- [x] Test RTL
- [ ] Test with screen-readers
- [x] Copy existing unit tests and ensure they all pass
- [x] Copy existing e2e tests and ensure they all pass (if any)
- [x] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [ ] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Additional notes
* This implementation uses MDC's CSS styles but Angular Material's overlay logic

### Known issues & visual differences
* The MDC-based `MatMenu` does not support increasing the elevation of a sub-menu, based on its depth
* MDC-based implementation is currently 0.86kb larger

**Comment by crisbeto** [comment]
Size comparison: https://github.com/mmalerba/mdc-size-comparison/tree/menu

**Comment by devversion** [comment]
It looks like the MDC-based menu does not use the divider of MDC. Currently our divider implementation is not following the spec (in the context of a menu surface item). See #14912
