### ISSUE TITLE
Build MDC-based tabs

### ISSUE THREAD

**Issue by mmalerba** [angular/components#16250]
### Tasks
- [x] Scaffold empty classes, assets, demo, build config, etc.
- [x] Stub existing component API
- [x] Hook up MDC foundation and adapter
- [x] Add remaining features on top of MDC implementation
- [x] Test dark theme
- [x] Test RTL
- [x] Test with screen-readers
- [x] Copy existing unit tests and ensure they all pass
- [x] Copy existing e2e tests and ensure they all pass (if any)
- [x] Verify SSR support in `universal-app/`
- [ ] Verify no size regression
- [x] Create test harness
- [ ] Create schematics for migration
- [ ] Create user documentation

### Known issues & visual differences
