### ISSUE TITLE
Switch build to bazel

### ISSUE THREAD

**Issue by jelbourn** [angular/components#8369]
- [x] ng_module rules for cdk (#8370)
- [x] build everything on CI (#8460, #8466)
- [x] ng_module rules for material (#8457)
- [ ] Update dev docs
- [x] cdk test rules (#9726)
- [ ] material test rules
~Create rule for template inlining~ (now part of `ng_package` rule)
- [x] Package cdk
- [x] Create rule for scss bundling (#10055)
- [ ] Package material
- [ ] Able to pass through browser flags for `web_test_suite`
- [ ] Able to serve dev app
- [ ] Everything for material-examples
- [ ] Everything for moment-adapter
- [ ] e2e test rules
- [ ] Get rid of css renaming genrules
- [ ] Get rid of scss partial filegroups
- [ ] Auto-format BUILD files and add skylint

**Comment by crisbeto** [comment]
Closing since we're mostly switched over to Bazel.
